// <auto-generated />
namespace TI.Configuration.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class add_code_to_cfg_and_settings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_code_to_cfg_and_settings));
        
        string IMigrationMetadata.Id
        {
            get { return "201906122340070_add_code_to_cfg_and_settings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
