// <auto-generated />
namespace TI.Configuration.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class code_fields_required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(code_fields_required));
        
        string IMigrationMetadata.Id
        {
            get { return "201906122341128_code_fields_required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
